### PR TITLE
Consolidate authentication for reusability

### PR DESCRIPTION
**Pull request by s-laugh**
### Description

List of proposed changes:

- Bringing the authentication checks of session into one spot to enable better reusability
- Set profile page to authenticate with new functions, converting to server page.

### CODE REVIEW

**Review by DaceyTom2 — COMMENTED** [review]
I'd recommend avoiding creating wrappers for libraries

**Comment by s-laugh** [comment]
> I'd recommend avoiding creating wrappers for libraries

Generally I agree, I feel like this makes for a good use case for an exception; as this is mocking a session object when we want to "bypass" the authentication.

Would like to hear more of your thoughts around this

**Comment by DaceyTom2** [comment]
bypassing authentication is just temporary until we get auth working with ECAS. The bypass should be removed after

**Comment by s-laugh** [comment]
Yup, not sure there is even much need for the bypass now... we have the dev keycloak for that.

**Pull request closed without merging**
