### PR TITLE
added search header

### PR DESCRIPTION
**Pull request by TishamIslam**
### Description
Added a search bar header section to the search results page.

List of proposed changes:

- Added search header and related component
- Added tests for search header

### CODE REVIEW

**Review by nibivi77 — COMMENTED** [review]
Quick comment, on mobile version (320px) it looks a little wierd.

image

**Comment by TishamIslam** [comment]
The weird mobile look should be fixed now!

**Review by DaceyTom2 — APPROVED** [review]
Amazing!

**Comment by TishamIslam** [comment]
Done in #63

**Pull request closed without merging**
